export const countryCodeNSNLengths: NSNLength[] = [
    { code: 'AD', label: 'Andorra', countryCode: '376', length: 6},
    { code: 'AE', label: 'United Arab Emirates', countryCode: '971', length: 9},
    { code: 'AF', label: 'Afghanistan', countryCode: '93', length: 9},
    { code: 'AG', label: 'Antigua and Barbuda', countryCode: '1-268', length: 10},
    { code: 'AI', label: 'Anguilla', countryCode: '1-264', length: 10},
    { code: 'AL', label: 'Albania', countryCode: '355', length: 9},
    { code: 'AM', label: 'Armenia', countryCode: '374', length: 6},
    { code: 'AO', label: 'Angola', countryCode: '244', length: 9},
    { code: 'AQ', label: 'Antarctica', countryCode: '672', length: 6},
    { code: 'AR', label: 'Argentina', countryCode: '54', length: [6,7,8]},					
    { code: 'AS', label: 'American Samoa', countryCode: '1-684', length: 10},
    { code: 'AT', label: 'Austria', countryCode: '43', length: [10,11]},			
    { code: 'AU', label: 'Australia', countryCode: '61', suggested: true, length: 9},
    { code: 'AW', label: 'Aruba', countryCode: '297', length: 7},
    { code: 'AX', label: 'Alland Islands', countryCode: '358', min: 7, max: 10},				
    { code: 'AZ', label: 'Azerbaijan', countryCode: '994', length: 9},
    { code: 'BA', label: 'Bosnia and Herzegovina', countryCode: '387', length: 8},
    { code: 'BB', label: 'Barbados', countryCode: '1-246', length: 10},
    { code: 'BD', label: 'Bangladesh', countryCode: '880', length: 10},
    { code: 'BE', label: 'Belgium', countryCode: '32', length: 9},
    { code: 'BF', label: 'Burkina Faso', countryCode: '226', length: 8},
    { code: 'BG', label: 'Bulgaria', countryCode: '359', length: 9},
    { code: 'BH', label: 'Bahrain', countryCode: '973', length: 8},
    { code: 'BI', label: 'Burundi', countryCode: '257', length: 8},
    { code: 'BJ', label: 'Benin', countryCode: '229', length: 8},
    { code: 'BL', label: 'Saint Barthelemy', countryCode: '590', length: 9},				
    { code: 'BM', label: 'Bermuda', countryCode: '1-441', length: 10},
    { code: 'BN', label: 'Brunei Darussalam', countryCode: '673', length: 7},
    { code: 'BO', label: 'Bolivia', countryCode: '591', length: 9},
    { code: 'BR', label: 'Brazil', countryCode: '55', length: 11},
    { code: 'BS', label: 'Bahamas', countryCode: '1-242', length: 10},
    { code: 'BT', label: 'Bhutan', countryCode: '975', length: 7},
    { code: 'BV', label: 'Bouvet Island', countryCode: '47',length: 10 },			
    { code: 'BW', label: 'Botswana', countryCode: '267', length: 7},
    { code: 'BY', label: 'Belarus', countryCode: '375', length: 9},
    { code: 'BZ', label: 'Belize', countryCode: '501', length: 7},
    { code: 'CA', label: 'Canada', countryCode: '1', suggested: true, length: 10},
    { code: 'CC', label: 'Cocos (Keeling) Islands', countryCode: '61', length: 10},			
    { code: 'CD', label: 'Congo, Democratic Republic of the', countryCode: '243', length: 7},	
    { code: 'CF', label: 'Central African Republic', countryCode: '236', length: 8},
    { code: 'CG', label: 'Congo, Republic of the', countryCode: '242', length: 9},	
    { code: 'CH', label: 'Switzerland', countryCode: '41', length: 9},
    { code: 'CI', label: "Cote d'Ivoire", countryCode: '225', length: 8},
    { code: 'CK', label: 'Cook Islands', countryCode: '682', length: 5},
    { code: 'CL', label: 'Chile', countryCode: '56', length: 9},
    { code: 'CM', label: 'Cameroon', countryCode: '237', length: 9},
    { code: 'CN', label: 'China', countryCode: '86', length: 11},
    { code: 'CO', label: 'Colombia', countryCode: '57', length: 10},
    { code: 'CR', label: 'Costa Rica', countryCode: '506', length: 8},
    { code: 'CU', label: 'Cuba', countryCode: '53', length: 8},
    { code: 'CV', label: 'Cape Verde', countryCode: '238', length: 7},
    { code: 'CW', label: 'Curacao', countryCode: '599', length: 7},
    { code: 'CX', label: 'Christmas Island', countryCode: '61', length: 9},	
    { code: 'CY', label: 'Cyprus', countryCode: '357', length: 8},
    { code: 'CZ', label: 'Czech Republic', countryCode: '420', length: 9},
    { code: 'DE', label: 'Germany', countryCode: '49', suggested: true, length: 10},
    { code: 'DJ', label: 'Djibouti', countryCode: '253', length: 10},
    { code: 'DK', label: 'Denmark', countryCode: '45', length: 8},
    { code: 'DM', label: 'Dominica', countryCode: '1-767', length: 10},
    { code: 'DO', label: 'Dominican Republic', countryCode: '1-809', length: 10},
    { code: 'DZ', label: 'Algeria', countryCode: '213', length: 9},
    { code: 'EC', label: 'Ecuador', countryCode: '593', length: 9},
    { code: 'EE', label: 'Estonia', countryCode: '372', length: 8},
    { code: 'EG', label: 'Egypt', countryCode: '20', length: 10},
    { code: 'EH', label: 'Western Sahara', countryCode: '212', length: 9},
    { code: 'ER', label: 'Eritrea', countryCode: '291', length: 7},	
    { code: 'ES', label: 'Spain', countryCode: '34', length: 9},
    { code: 'ET', label: 'Ethiopia', countryCode: '251', length: 9},
    { code: 'FI', label: 'Finland', countryCode: '358', min: 9, max: 11},
    { code: 'FJ', label: 'Fiji', countryCode: '679', length: 7},
    { code: 'FK', label: 'Falkland Islands (Malvinas)', countryCode: '500', length: 5},
    { code: 'FM', label: 'Micronesia, Federated States of', countryCode: '691', length: 7},
    { code: 'FO', label: 'Faroe Islands', countryCode: '298', length: 5},
    { code: 'FR', label: 'France', countryCode: '33', suggested: true, length: 9},
    { code: 'GA', label: 'Gabon', countryCode: '241', length: 7},
    { code: 'GB', label: 'United Kingdom', countryCode: '44', length: 10},
    { code: 'GD', label: 'Grenada', countryCode: '1-473', length: 10},
    { code: 'GE', label: 'Georgia', countryCode: '995', length: 9},
    { code: 'GF', label: 'French Guiana', countryCode: '594', length: 9},
    { code: 'GG', label: 'Guernsey', countryCode: '44', length: 10},
    { code: 'GH', label: 'Ghana', countryCode: '233', length: 9},
    { code: 'GI', label: 'Gibraltar', countryCode: '350', length: 8},
    { code: 'GL', label: 'Greenland', countryCode: '299', length: 6},
    { code: 'GM', label: 'Gambia', countryCode: '220', length: 7},
    { code: 'GN', label: 'Guinea', countryCode: '224', length: 9},
    { code: 'GP', label: 'Guadeloupe', countryCode: '590', length: 9},
    { code: 'GQ', label: 'Equatorial Guinea', countryCode: '240', length: 9},
    { code: 'GR', label: 'Greece', countryCode: '30', length: 10},
    { code: 'GS', label: 'South Georgia and the South Sandwich Islands', countryCode: '500', length: 5},	
    { code: 'GT', label: 'Guatemala', countryCode: '502', length: 8},
    { code: 'GU', label: 'Guam', countryCode: '1-671', length: 10},
    { code: 'GW', label: 'Guinea-Bissau', countryCode: '245', length: 9},
    { code: 'GY', label: 'Guyana', countryCode: '592', length: 7},
    { code: 'HK', label: 'Hong Kong', countryCode: '852', length: 8},
    { code: 'HM', label: 'Heard Island and McDonald Islands', countryCode: '672',length: 10 },		
    { code: 'HN', label: 'Honduras', countryCode: '504', length: 8},
    { code: 'HR', label: 'Croatia', countryCode: '385', length: 9},
    { code: 'HT', label: 'Haiti', countryCode: '509', length: 8},
    { code: 'HU', label: 'Hungary', countryCode: '36', length: 9},
    { code: 'ID', label: 'Indonesia', countryCode: '62', length: 11},
    { code: 'IE', label: 'Ireland', countryCode: '353', length: 9},
    { code: 'IL', label: 'Israel', countryCode: '972', length: 9},
    { code: 'IM', label: 'Isle of Man', countryCode: '44', length: 10},
    { code: 'IN', label: 'India', countryCode: '91', length: 10},
    { code: 'IO', label: 'British Indian Ocean Territory', countryCode: '246', length: 7},
    { code: 'IQ', label: 'Iraq', countryCode: '964', length: 10},	
    { code: 'IR', label: 'Iran, Islamic Republic of', countryCode: '98', length: 11},
    { code: 'IS', label: 'Iceland', countryCode: '354', length: 7},
    { code: 'IT', label: 'Italy', countryCode: '39', length: 10},
    { code: 'JE', label: 'Jersey', countryCode: '44', length: 10},
    { code: 'JM', label: 'Jamaica', countryCode: '1-876', length: 10},
    { code: 'JO', label: 'Jordan', countryCode: '962', length: [8,9]},	
    { code: 'JP', label: 'Japan', countryCode: '81', suggested: true },
    { code: 'KE', label: 'Kenya', countryCode: '254', length: 10},
    { code: 'KG', label: 'Kyrgyzstan', countryCode: '996', length: 9},
    { code: 'KH', label: 'Cambodia', countryCode: '855', length: 9},
    { code: 'KI', label: 'Kiribati', countryCode: '686', length: 8},
    { code: 'KM', label: 'Comoros', countryCode: '269', length: 7},
    { code: 'KN', label: 'Saint Kitts and Nevis', countryCode: '1-869', length: 10},
    { code: 'KP', label: "Korea, Democratic People's Republic of", countryCode: '850', length: [4,6,7,13]},	
    { code: 'KR', label: 'Korea, Republic of', countryCode: '82', length: [7,8]},	
    { code: 'KW', label: 'Kuwait', countryCode: '965', length: 8},
    { code: 'KY', label: 'Cayman Islands', countryCode: '1-345', length: 7},
    { code: 'KZ', label: 'Kazakhstan', countryCode: '7', length: 10},
    { code: 'LA', label: "Lao People's Democratic Republic", countryCode: '856', length: [8,9]},
    { code: 'LB', label: 'Lebanon', countryCode: '961', length: [7,8]},	
    { code: 'LC', label: 'Saint Lucia', countryCode: '1-758', length: 7},
    { code: 'LI', label: 'Liechtenstein', countryCode: '423', length: 7},
    { code: 'LK', label: 'Sri Lanka', countryCode: '94', length: 7},
    { code: 'LR', label: 'Liberia', countryCode: '231', length: [8,9]},	
    { code: 'LS', label: 'Lesotho', countryCode: '266', length: 8},
    { code: 'LT', label: 'Lithuania', countryCode: '370', length: 8},
    { code: 'LU', label: 'Luxembourg', countryCode: '352', length: 9},
    { code: 'LV', label: 'Latvia', countryCode: '371', length: 8},
    { code: 'LY', label: 'Libya', countryCode: '218', length: 10},
    { code: 'MA', label: 'Morocco', countryCode: '212', length: 9},
    { code: 'MC', label: 'Monaco', countryCode: '377', length: 8},
    { code: 'MD', label: 'Moldova, Republic of', countryCode: '373', length: 8},
    { code: 'ME', label: 'Montenegro', countryCode: '382', length: 8},
    { code: 'MF', label: 'Saint Martin (French part)', countryCode: '590', length: 6},
    { code: 'MG', label: 'Madagascar', countryCode: '261', length: 7},
    { code: 'MH', label: 'Marshall Islands', countryCode: '692', length: 7},
    { code: 'MK', label: 'Macedonia, the Former Yugoslav Republic of', countryCode: '389', length: 8},
    { code: 'ML', label: 'Mali', countryCode: '223', length: 8},
    { code: 'MM', label: 'Myanmar', countryCode: '95', min: 7, max: 10},					
    { code: 'MN', label: 'Mongolia', countryCode: '976', length: 8},
    { code: 'MO', label: 'Macao', countryCode: '853', length: 8},
    { code: 'MP', label: 'Northern Mariana Islands', countryCode: '1-670', length: 7},
    { code: 'MQ', label: 'Martinique', countryCode: '596', length: 9},
    { code: 'MR', label: 'Mauritania', countryCode: '222', length: 8},
    { code: 'MS', label: 'Montserrat', countryCode: '1-664', length: 10},
    { code: 'MT', label: 'Malta', countryCode: '356', length: 8},
    { code: 'MU', label: 'Mauritius', countryCode: '230', length: 8},
    { code: 'MV', label: 'Maldives', countryCode: '960', length: 7},
    { code: 'MW', label: 'Malawi', countryCode: '265', length: [7,8,9]},	
    { code: 'MX', label: 'Mexico', countryCode: '52', length: 10},
    { code: 'MY', label: 'Malaysia', countryCode: '60', length: 7},
    { code: 'MZ', label: 'Mozambique', countryCode: '258', length: 12},
    { code: 'NA', label: 'Namibia', countryCode: '264', length: 7},
    { code: 'NC', label: 'New Caledonia', countryCode: '687', length: 6},
    { code: 'NE', label: 'Niger', countryCode: '227', length: 8},
    { code: 'NF', label: 'Norfolk Island', countryCode: '672', length: 6},
    { code: 'NG', label: 'Nigeria', countryCode: '234', length: 8},
    { code: 'NI', label: 'Nicaragua', countryCode: '505', length: 8},
    { code: 'NL', label: 'Netherlands', countryCode: '31', length: 9},
    { code: 'NO', label: 'Norway', countryCode: '47', length: 8},
    { code: 'NP', label: 'Nepal', countryCode: '977', length: 10},
    { code: 'NR', label: 'Nauru', countryCode: '674', length: 7},
    { code: 'NU', label: 'Niue', countryCode: '683', length: 4},
    { code: 'NZ', label: 'New Zealand', countryCode: '64', length: [8,9]},	
    { code: 'OM', label: 'Oman', countryCode: '968', length: 8},
    { code: 'PA', label: 'Panama', countryCode: '507', length: 8},
    { code: 'PE', label: 'Peru', countryCode: '51', length: 9},
    { code: 'PF', label: 'French Polynesia', countryCode: '689', length: 8},
    { code: 'PG', label: 'Papua New Guinea', countryCode: '675', length: 8},	
    { code: 'PH', label: 'Philippines', countryCode: '63', length: 10},
    { code: 'PK', label: 'Pakistan', countryCode: '92', length: 10},
    { code: 'PL', label: 'Poland', countryCode: '48', length: 9},
    { code: 'PM', label: 'Saint Pierre and Miquelon', countryCode: '508', length: 6},
    { code: 'PN', label: 'Pitcairn', countryCode: '870', length: 9},	
    { code: 'PR', label: 'Puerto Rico', countryCode: '1', length: 10},
    { code: 'PS', label: 'Palestine, State of', countryCode: '970', length: 9},					
    { code: 'PT', label: 'Portugal', countryCode: '351', length: 9},
    { code: 'PW', label: 'Palau', countryCode: '680', length: 7},
    { code: 'PY', label: 'Paraguay', countryCode: '595', length: 9},
    { code: 'QA', label: 'Qatar', countryCode: '974', length: 8},
    { code: 'RE', label: 'Reunion', countryCode: '262', length: 10},
    { code: 'RO', label: 'Romania', countryCode: '40', length: 10},
    { code: 'RS', label: 'Serbia', countryCode: '381', length: 9},
    { code: 'RU', label: 'Russian Federation', countryCode: '7', length: 10},
    { code: 'RW', label: 'Rwanda', countryCode: '250', length: 9},
    { code: 'SA', label: 'Saudi Arabia', countryCode: '966', length: 9},
    { code: 'SB', label: 'Solomon Islands', countryCode: '677', length: 7},
    { code: 'SC', label: 'Seychelles', countryCode: '248', length: 7},
    { code: 'SD', label: 'Sudan', countryCode: '249', length: 7},
    { code: 'SE', label: 'Sweden', countryCode: '46', length: 7},
    { code: 'SG', label: 'Singapore', countryCode: '65', length: 8},
    { code: 'SH', label: 'Saint Helena', countryCode: '290', length: 4},
    { code: 'SI', label: 'Slovenia', countryCode: '386', length: 9},
    { code: 'SJ', label: 'Svalbard and Jan Mayen', countryCode: '47', length: 8},	
    { code: 'SK', label: 'Slovakia', countryCode: '421', length: 9},
    { code: 'SL', label: 'Sierra Leone', countryCode: '232', length: 8},
    { code: 'SM', label: 'San Marino', countryCode: '378', length: 10},	
    { code: 'SN', label: 'Senegal', countryCode: '221', length: 9},
    { code: 'SO', label: 'Somalia', countryCode: '252', length: [8,9]},	
    { code: 'SR', label: 'Suriname', countryCode: '597', length: [6,7]},	
    { code: 'SS', label: 'South Sudan', countryCode: '211', length: 7},
    { code: 'ST', label: 'Sao Tome and Principe', countryCode: '239', length: 7},
    { code: 'SV', label: 'El Salvador', countryCode: '503', length: 8},
    { code: 'SX', label: 'Sint Maarten (Dutch part)', countryCode: '1-721', length: 10},
    { code: 'SY', label: 'Syrian Arab Republic', countryCode: '963', length: 7},					
    { code: 'SZ', label: 'Swaziland', countryCode: '268', length: 8},	
    { code: 'TC', label: 'Turks and Caicos Islands', countryCode: '1-649', length: 10},
    { code: 'TD', label: 'Chad', countryCode: '235', length: 6},
    { code: 'TF', label: 'French Southern Territories', countryCode: '262', length: 10},
    { code: 'TG', label: 'Togo', countryCode: '228', length: 8},
    { code: 'TH', label: 'Thailand', countryCode: '66', length: 9},
    { code: 'TJ', label: 'Tajikistan', countryCode: '992', length: 9},	
    { code: 'TK', label: 'Tokelau', countryCode: '690', length: 5},
    { code: 'TL', label: 'Timor-Leste', countryCode: '670', length: 7},
    { code: 'TM', label: 'Turkmenistan', countryCode: '993', length: 8},	
    { code: 'TN', label: 'Tunisia', countryCode: '216', length: 8},
    { code: 'TO', label: 'Tonga', countryCode: '676', length: 5},
    { code: 'TR', label: 'Turkey', countryCode: '90', length: 11},
    { code: 'TT', label: 'Trinidad and Tobago', countryCode: '1-868', length: 7},
    { code: 'TV', label: 'Tuvalu', countryCode: '688', length: 5},
    { code: 'TW', label: 'Taiwan, Province of China', countryCode: '886', length: 9},	
    { code: 'TZ', label: 'United Republic of Tanzania', countryCode: '255', length: 7},
    { code: 'UA', label: 'Ukraine', countryCode: '380', length: 9},
    { code: 'UG', label: 'Uganda', countryCode: '256', length: 7},
    { code: 'US', label: 'United States', countryCode: '1', suggested: true, length: 10},
    { code: 'UY', label: 'Uruguay', countryCode: '598', length: 8},
    { code: 'UZ', label: 'Uzbekistan', countryCode: '998', length: 9},
    { code: 'VA', label: 'Holy See (Vatican City State)', countryCode: '379' ,length: 10},			
    { code: 'VC', label: 'Saint Vincent and the Grenadines', countryCode: '1-784', length: 7},
    { code: 'VE', label: 'Venezuela', countryCode: '58', length: 7},
    { code: 'VG', label: 'British Virgin Islands', countryCode: '1-284', length: 7},
    { code: 'VI', label: 'US Virgin Islands', countryCode: '1-340', length: 10},
    { code: 'VN', label: 'Vietnam', countryCode: '84', length: 9},
    { code: 'VU', label: 'Vanuatu', countryCode: '678', length: 5},
    { code: 'WF', label: 'Wallis and Futuna', countryCode: '681', length: 6},
    { code: 'WS', label: 'Samoa', countryCode: '685', length: [5,6,7]},	 
    { code: 'XK', label: 'Kosovo', countryCode: '383', length: 8},	
    { code: 'YE', label: 'Yemen', countryCode: '967', length: 9},
    { code: 'YT', label: 'Mayotte', countryCode: '262', length: 9},
    { code: 'ZA', label: 'South Africa', countryCode: '27', length: 9},
    { code: 'ZM', label: 'Zambia', countryCode: '260', length: 9},
    { code: 'ZW', label: 'Zimbabwe', countryCode: '263', length: 9},
];

export function getNSNLength(countryCode: string): number | number[] | null {
    const countryData = countryCodeNSNLengths.find((data) => data.countryCode === countryCode);
    if (countryData) {
      if (Array.isArray(countryData.length)) {
        return countryData.length;
      } else {
        return countryData.length;
      }
    } else {
      return null; 
    }
  }

export interface NSNLength {
    code: string;
    label: string;
    countryCode: string;
    length?: any | null;
    suggested?: boolean | null;
    min?: number | null;
    max?: number | null;
}

